language: d
sudo: false

services:
  - cassandra

env:
  - USE_VIBED=1
  - USE_VIBED=0

script:
  - |-
    if [ $USE_VIBED == 1 ]; then
      dub test --compiler=$DC
    else
      dub test --compiler=$DC --config=library-no-vibe
    fi
